# Generated by Django 5.2.4 on 2025-07-24 03:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_featured_blog_blog_home_page_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='small_content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
