# Generated by Django 5.2.4 on 2025-07-17 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauthapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default=datetime.datetime(2025, 7, 17, 3, 16, 57, 727951, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
